---
# defaults for packages role

packages_list:
  - build-essential
  - python3
  - python3-venv
  - python3-pip
  - gcc
  - make

# On some distros package names differ; override in group_vars if needed
python_package: python3-pip
